//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinglePageCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BigSlide : Block
    {
        public int Items { get; set; }
        public bool Nav { get; set; }
        public bool Dot { get; set; }
        public bool Autoplay { get; set; }
    }
}
