//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinglePageCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form : Block
    {
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
    }
}
